"use client";
import React, { useState } from "react";

interface Account {
  name: string;
  username: string;
  code: string;
  icon: string;
  secretKey: string;
  type: string;
  interval: string;
  id: string;
  addedDate: string;
}

interface AddAccountProps {
  onClose: () => void;
  onAdd: (account: Account) => void;
}

// AddAccount Modal Component
function AddAccount({ onClose, onAdd }: AddAccountProps) {
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [qrData, setQrData] = useState<{
    secret: string;
    qr: string;
    otpauth: string;
  } | null>(null);
  const [formData, setFormData] = useState({
    accountName: "",
    email: "",
    secretKey: "",
    type: "TOTP",
    interval: "30",
  });

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>,
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleNext = async () => {
    if (step === 1 && formData.accountName && formData.email) {
      setLoading(true);

      try {
        // Call the API to get QR code and secret
        const response = await fetch("/api/2fa/setup", {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        });

        const data = await response.json();

        if (data.success && data.data) {
          setQrData({
            secret: data.data.secret,
            qr: data.data.qr,
            otpauth: data.data.otpauth,
          });

          // Auto-fill the secret key
          setFormData((prev) => ({
            ...prev,
            secretKey: data.data.secret,
          }));

          setStep(2);
        } else {
          alert(data.message || "Failed to generate QR code");
        }
      } catch (error) {
        console.error("Error fetching QR code:", error);
        alert("Failed to generate QR code. Please try again.");
      } finally {
        setLoading(false);
      }
    }
  };

  const handleBack = () => {
    setStep(1);
  };

  const handleSubmit = () => {
    if (formData.secretKey) {
      const initial = formData.accountName.charAt(0).toUpperCase();

      const newAccount = {
        name: formData.accountName,
        username: formData.email,
        code: "000 000", // Will be generated by TOTP
        icon: initial,
        secretKey: formData.secretKey,
        type: formData.type,
        interval: formData.interval,
        id: Date.now().toString(),
        addedDate: new Date().toISOString(),
      };

      onAdd(newAccount);
      onClose();
    }
  };

  const handleManualEntry = () => {
    setFormData((prev) => ({
      ...prev,
      secretKey: "",
    }));
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 z-50">
      <div className="bg-slate-800 rounded-2xl shadow-2xl w-full max-w-md overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-600 to-blue-500 p-6 relative">
          <button
            onClick={onClose}
            className="absolute top-4 right-4 text-white/80 hover:text-white transition-colors"
            disabled={loading}
          >
            <svg
              className="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
          <h2 className="text-2xl font-bold text-white">Add New Account</h2>
          <p className="text-blue-100 mt-1">Step {step} of 2</p>
        </div>

        {/* Progress Bar */}
        <div className="h-1 bg-slate-700">
          <div
            className="h-full bg-blue-500 transition-all duration-300"
            style={{ width: `${(step / 2) * 100}%` }}
          />
        </div>

        {/* Loading Overlay */}
        {loading && (
          <div className="absolute inset-0 bg-slate-900/80 backdrop-blur-sm flex items-center justify-center z-10">
            <div className="text-center">
              <div className="w-16 h-16 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
              <p className="text-white font-medium">Generating QR Code...</p>
              <p className="text-slate-400 text-sm mt-1">Please wait</p>
            </div>
          </div>
        )}

        {/* Content */}
        <div className="p-6">
          {step === 1 ? (
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Account Name
                </label>
                <input
                  type="text"
                  name="accountName"
                  value={formData.accountName}
                  onChange={handleInputChange}
                  placeholder="e.g., GitHub, Google, AWS"
                  className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Email/Username
                </label>
                <input
                  type="text"
                  name="email"
                  value={formData.email}
                  onChange={handleInputChange}
                  placeholder="user@example.com"
                  className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Type
                </label>
                <select
                  name="type"
                  value={formData.type}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="TOTP">TOTP (Time-based)</option>
                  <option value="HOTP">HOTP (Counter-based)</option>
                </select>
              </div>

              {formData.type === "TOTP" && (
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">
                    Interval (seconds)
                  </label>
                  <select
                    name="interval"
                    value={formData.interval}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  >
                    <option value="30">30 seconds</option>
                    <option value="60">60 seconds</option>
                  </select>
                </div>
              )}
            </div>
          ) : (
            <div className="space-y-4">
              <div className="text-center py-4">
                <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-500/20 rounded-full mb-4">
                  <svg
                    className="w-8 h-8 text-blue-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z"
                    />
                  </svg>
                </div>
                <h3 className="text-lg font-semibold text-white mb-2">
                  Scan QR Code
                </h3>
                <p className="text-slate-400 text-sm">
                  Scan this code with your authenticator app
                </p>
              </div>

              {/* QR Code Display */}
              {qrData && (
                <div className="bg-white p-4 rounded-xl mx-auto w-fit">
                  <img src={qrData.qr} alt="QR Code" className="w-48 h-48" />
                </div>
              )}

              <div className="flex items-center gap-3">
                <div className="flex-1 h-px bg-slate-600"></div>
                <span className="text-slate-500 text-sm">OR</span>
                <div className="flex-1 h-px bg-slate-600"></div>
              </div>

              {/* Manual Entry Key Display */}
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Manual Entry Key
                </label>
                <div className="relative">
                  <input
                    type="text"
                    name="secretKey"
                    value={formData.secretKey}
                    onChange={handleInputChange}
                    placeholder="Enter your secret key"
                    className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent font-mono text-sm"
                    readOnly={!!qrData}
                  />
                  {qrData && (
                    <button
                      onClick={() => {
                        navigator.clipboard.writeText(formData.secretKey);
                      }}
                      className="absolute right-2 top-1/2 -translate-y-1/2 p-2 hover:bg-slate-600 rounded-lg transition-colors"
                      title="Copy to clipboard"
                    >
                      <svg
                        className="w-4 h-4 text-slate-400"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                        />
                      </svg>
                    </button>
                  )}
                </div>
                <p className="text-slate-500 text-xs mt-2">
                  {qrData
                    ? "Use this key if you can't scan the QR code"
                    : "The secret key is provided by the service you're adding"}
                </p>
              </div>

              {qrData && (
                <button
                  onClick={handleManualEntry}
                  className="w-full text-sm text-blue-400 hover:text-blue-300 transition-colors"
                >
                  Enter a different secret key manually
                </button>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-6 bg-slate-900/50 border-t border-slate-700 flex gap-3">
          {step === 2 && (
            <button
              onClick={handleBack}
              disabled={loading}
              className="flex-1 px-4 py-3 bg-slate-700 hover:bg-slate-600 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg transition-colors font-medium"
            >
              Back
            </button>
          )}
          {step === 1 ? (
            <button
              onClick={handleNext}
              disabled={!formData.accountName || !formData.email || loading}
              className="flex-1 px-4 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-700 disabled:cursor-not-allowed text-white rounded-lg transition-colors font-medium"
            >
              {loading ? "Loading..." : "Next"}
            </button>
          ) : (
            <button
              onClick={handleSubmit}
              disabled={!formData.secretKey || loading}
              className="flex-1 px-4 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-700 disabled:cursor-not-allowed text-white rounded-lg transition-colors font-medium"
            >
              Add Account
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

export default AddAccount;
