"use client";
import React, { useState, useEffect } from "react";

interface Account {
  name: string;
  username: string;
  code: string;
  icon: string;
  secretKey: string;
  type: string;
  interval: string;
  id: string;
  addedDate: string;
}

interface AddAccountProps {
  onClose: () => void;
  onAdd: (account: Account) => void;
}

// AddAccount Modal Component
function AddAccount({ onClose, onAdd }: AddAccountProps) {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState({
    accountName: "",
    email: "",
    secretKey: "",
    type: "TOTP",
    interval: "30",
  });

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>,
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleNext = () => {
    if (step === 1 && formData.accountName && formData.email) {
      setStep(2);
    }
  };

  const handleBack = () => {
    setStep(1);
  };

  const handleSubmit = () => {
    if (formData.secretKey) {
      const initial = formData.accountName.charAt(0).toUpperCase();

      const newAccount = {
        name: formData.accountName,
        username: formData.email,
        code: "000 000", // Will be generated by TOTP
        icon: initial,
        secretKey: formData.secretKey,
        type: formData.type,
        interval: formData.interval,
        id: Date.now().toString(),
        addedDate: new Date().toISOString(),
      };

      onAdd(newAccount);
      onClose();
    }
  };

  const handleScanQR = () => {
    alert("QR Scanner would open here in a real implementation");
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 z-50">
      <div className="bg-slate-800 rounded-2xl shadow-2xl w-full max-w-md overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-600 to-blue-500 p-6 relative">
          <button
            onClick={onClose}
            className="absolute top-4 right-4 text-white/80 hover:text-white transition-colors"
          >
            <svg
              className="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
          <h2 className="text-2xl font-bold text-white">Add New Account</h2>
          <p className="text-blue-100 mt-1">Step {step} of 2</p>
        </div>

        {/* Progress Bar */}
        <div className="h-1 bg-slate-700">
          <div
            className="h-full bg-blue-500 transition-all duration-300"
            style={{ width: `${(step / 2) * 100}%` }}
          />
        </div>

        {/* Content */}
        <div className="p-6">
          {step === 1 ? (
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Account Name
                </label>
                <input
                  type="text"
                  name="accountName"
                  value={formData.accountName}
                  onChange={handleInputChange}
                  placeholder="e.g., GitHub, Google, AWS"
                  className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Email/Username
                </label>
                <input
                  type="text"
                  name="email"
                  value={formData.email}
                  onChange={handleInputChange}
                  placeholder="user@example.com"
                  className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Type
                </label>
                <select
                  name="type"
                  value={formData.type}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="TOTP">TOTP (Time-based)</option>
                  <option value="HOTP">HOTP (Counter-based)</option>
                </select>
              </div>

              {formData.type === "TOTP" && (
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">
                    Interval (seconds)
                  </label>
                  <select
                    name="interval"
                    value={formData.interval}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  >
                    <option value="30">30 seconds</option>
                    <option value="60">60 seconds</option>
                  </select>
                </div>
              )}
            </div>
          ) : (
            <div className="space-y-4">
              <div className="text-center py-4">
                <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-500/20 rounded-full mb-4">
                  <svg
                    className="w-8 h-8 text-blue-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z"
                    />
                  </svg>
                </div>
                <h3 className="text-lg font-semibold text-white mb-2">
                  Add Secret Key
                </h3>
                <p className="text-slate-400 text-sm">
                  Enter your secret key or scan a QR code
                </p>
              </div>

              <button
                onClick={handleScanQR}
                className="w-full px-4 py-3 bg-slate-700 hover:bg-slate-600 border border-slate-600 rounded-lg text-white transition-colors flex items-center justify-center gap-2"
              >
                <svg
                  className="w-5 h-5"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z"
                  />
                </svg>
                Scan QR Code
              </button>

              <div className="flex items-center gap-3">
                <div className="flex-1 h-px bg-slate-600"></div>
                <span className="text-slate-500 text-sm">OR</span>
                <div className="flex-1 h-px bg-slate-600"></div>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Secret Key
                </label>
                <input
                  type="text"
                  name="secretKey"
                  value={formData.secretKey}
                  onChange={handleInputChange}
                  placeholder="Enter your secret key"
                  className="w-full px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent font-mono text-sm"
                />
                <p className="text-slate-500 text-xs mt-2">
                  The secret key is provided by the service you're adding
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-6 bg-slate-900/50 border-t border-slate-700 flex gap-3">
          {step === 2 && (
            <button
              onClick={handleBack}
              className="flex-1 px-4 py-3 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors font-medium"
            >
              Back
            </button>
          )}
          {step === 1 ? (
            <button
              onClick={handleNext}
              disabled={!formData.accountName || !formData.email}
              className="flex-1 px-4 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-700 disabled:cursor-not-allowed text-white rounded-lg transition-colors font-medium"
            >
              Next
            </button>
          ) : (
            <button
              onClick={handleSubmit}
              disabled={!formData.secretKey}
              className="flex-1 px-4 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-700 disabled:cursor-not-allowed text-white rounded-lg transition-colors font-medium"
            >
              Add Account
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

// Main CodeDisplay Component
function CodeDisplay() {
  const [showAddAccount, setShowAddAccount] = useState(false);
  const [accounts, setAccounts] = useState([
    {
      name: "GitHub",
      username: "user@email.com",
      code: "123 456",
      icon: "G",
      id: "1",
    },
    {
      name: "Google",
      username: "user@gmail.com",
      code: "789 012",
      icon: "G",
      id: "2",
    },
    { name: "AWS", username: "admin", code: "345 678", icon: "A", id: "3" },
  ]);

  const handleAddAccount = (newAccount: Account) => {
    setAccounts((prev) => [...prev, newAccount]);
  };

  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code.replace(/\s/g, ""));
    // You could add a toast notification here
  };

  const handleDeleteAccount = (id: string) => {
    setAccounts((prev) => prev.filter((account) => account.id !== id));
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-white">Your Codes</h2>
        <button
          onClick={() => setShowAddAccount(true)}
          className="px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors flex items-center gap-2"
        >
          <svg
            className="w-4 h-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 4v16m8-8H4"
            />
          </svg>
          Add Account
        </button>
      </div>

      {/* Code Cards */}
      {accounts.length > 0 &&
        accounts.map((account) => (
          <div
            key={account.id}
            className="bg-slate-800/50 backdrop-blur rounded-xl border border-slate-700 p-5 hover:border-blue-500/50 transition-colors"
          >
            <div className="flex items-center justify-between">
              {/* Account Info */}
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-blue-500/20 rounded-lg flex items-center justify-center">
                  <span className="text-xl font-bold text-blue-400">
                    {account.icon}
                  </span>
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-white">
                    {account.name}
                  </h3>
                  <p className="text-sm text-slate-400">{account.username}</p>
                </div>
              </div>

              {/* Code Display */}
              <div className="text-right">
                <div className="text-3xl font-mono font-bold text-white tracking-wider mb-1">
                  {account.code}
                </div>
                {/* Timer Progress */}
                <div className="w-32 h-1 bg-slate-700 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-blue-500 transition-all duration-1000"
                    style={{ width: "60%" }}
                  ></div>
                </div>
                <p className="text-xs text-slate-400 mt-1">18s remaining</p>
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-2 mt-4 pt-4 border-t border-slate-700">
              <button
                onClick={() => handleCopyCode(account.code)}
                className="flex-1 px-3 py-2 bg-slate-700 hover:bg-slate-600 text-white text-sm rounded-lg transition-colors flex items-center justify-center gap-2"
              >
                <svg
                  className="w-4 h-4"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                  />
                </svg>
                Copy
              </button>
              <button
                onClick={() => handleDeleteAccount(account.id)}
                className="px-3 py-2 bg-slate-700 hover:bg-red-600 text-white text-sm rounded-lg transition-colors"
              >
                <svg
                  className="w-4 h-4"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                  />
                </svg>
              </button>
            </div>
          </div>
        ))}

      {/* Empty State */}
      {accounts.length === 0 && (
        <div className="text-center py-16">
          <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg
              className="w-10 h-10 text-slate-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
              />
            </svg>
          </div>
          <h3 className="text-xl font-semibold text-white mb-2">
            No accounts yet
          </h3>
          <p className="text-slate-400 mb-6">
            Add your first 2FA account to get started
          </p>
          <button
            onClick={() => setShowAddAccount(true)}
            className="px-6 py-3 bg-blue-500 hover:bg-blue-600 text-white font-semibold rounded-lg transition-colors"
          >
            Add Your First Account
          </button>
        </div>
      )}

      {/* Add Account Modal */}
      {showAddAccount && (
        <AddAccount
          onClose={() => setShowAddAccount(false)}
          onAdd={handleAddAccount}
        />
      )}
    </div>
  );
}

export default CodeDisplay;
